INSERT INTO middle.subject (name, tutor)
VALUES
('Theory of computation', 'Alex Johnson'),
('VLSI design', 'Emily Miller'),
('Database', 'Daniel Walker'),
('Cryptanalysis', 'Olivia Davis'),
('High-performance', 'Ethan Mitchell'),
('Fault-tolerant', 'Sophia Anderson'),
('History of computer hardware', 'Ava Carter'),
('Humanistic informatics', 'Mason Turner'),
('Numerical analysis', 'Isabella Parker'),
('Algebraic (symbolic) computation', 'Noah Evans'),
('Distributed computing', 'Mia Wright'),
('Computational mathematics', 'Aiden Hayes'),
('Object-oriented programming', 'Chloe Bennett'),
('Algorithms', 'Lucas Harrison'),
('Algorithms', 'Grace Foster'),
('Compilers', 'Jackson Taylor'),
('Robotics (outline)', 'Lily Robinson'),
('Information science (outline)', 'Caleb Brooks'),
('Community informatics', 'Ella Reed'),
('Humanistic informatics', 'Logan Cooper'),
('Computing in social sciences, arts, humanities', 'Addison Hughes'),
('', 'Owen Nelson'),
('LLM', 'Zoey White'),
('Data structures', 'Wyatt Morgan'),
('Architecture', 'Harper King'),
('Computer communications (networks)', 'Gabriel Harris'),
('Computability', 'Scarlett Lewis'),
('Concurrency', 'Samuel Carter'),
('Concurrency theory', 'Amelia Scott'),
('Concurrency', 'Henry Adams'),
('Concurrency practics', 'Abigail Hall'),
('Data science', 'Dylan Baker'),
('Databases', 'Penelope Ward'),
('Operating systems', 'Levi Myers'),
('Computational geometry', 'Nora Fisher'),
('Randomized algorithms', 'Leo Richardson'),
('Information', 'Stella Morris'),
('Informatica', 'Connor Reed'),
('Infocratia', 'Evelyn Turner'),
('Distributed algorithms', 'Oliver Hill'),
('Parallel algorithms', 'Ava Richards'),
('Ubiquitous computing', 'Mason Cole'),
('Computer-programming', 'Sophia Parker'),
('Formal methods (Formal verification)', 'Jackson Bennett'),
('Paradigms', 'Lily Sullivan'),
('Object-oriented programming', 'Caleb Johnson'),
('Knowledge', 'Addison Foster'),
('Quantum', 'Lucas Taylor'),
('AI', 'Grace Martin'),
('Pinanije', 'Teacher John');
